spring:
  data:
    mongodb:
      uri: ${DB_URL}
      host: ${HOST:localhost}
      port: ${PORT:27017}
      database: ${DB_DATABASE:chatme}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: admin

web:
  origin: ${ORIGIN}

